services:
    Kunstmaan\Rest\MediaBundle\Controller\MediaController:
        public: true
        arguments:
            - '@kunstmaan_media.media_manager'
            - '@filesystem'
            - '@doctrine.orm.default_entity_manager'
        calls:
            - [setViewHandler, ['@fos_rest.view_handler.default']]
