nelmio_api_doc:
  documentation:
    components:
      schemas:
        Media:
          title: "Media"
          type: "object"
          properties:
            id:
              type: "integer"
            name:
              type: "string"
            description:
              type: "string"
            copyright:
              type: "string"
            url:
              type: "string"
            originalFilename:
              type: "string"
            folder:
              type: "object"
              allOf:
                - $ref: '#/components/schemas/Folder'
            contentType:
              type: "string"
            metadata:
              type: "string"
            filetype:
              type: "string"

        Folder:
          properties:
            id:
              type: "integer"
            name:
              type: "string"
            internalName:
              type: "string"
            rel:
              type: "string"
            parentId:
              type: "integer"
            lft:
              type: "integer"
            rgt:
              type: "integer"
            lvl:
              type: "integer"

        PostFolder:
          type: "object"
          properties:
            name:
              type: "string"
            internalName:
              type: "string"
            rel:
              type: "string"

        UploadMedia:
          title: "UploadMedia"
          type: "object"
          properties:
            content:
              type: "string"
              required: false
            url:
              type: "string"
              required: false
            name:
              type: "string"
            description:
              type: "string"
            copyRight:
              type: "string"
            folderId:
              type: "integer"
              default: 1

        putMedia:
          title: "UploadMedia"
          type: "object"
          properties:
            name:
              type: "string"
              required: false
            description:
              type: "string"
              required: false
            copyRight:
              type: "string"
              required: false
            folderId:
              type: "integer"
              required: false

        MediaList:
          properties:
            media:
              type: "array"
              items:
                allOf:
                  - $ref: '#/components/schemas/Media'
          title: "MediaList"
          required: ["items"]
          type: "object"

        FolderList:
          properties:
            folder:
              type: "array"
              items:
                allOf:
                  - $ref: '#/components/schemas/Folder'
          title: "FolderList"
          required: ["items"]
          type: "object"
