kunstmaan_api_users:
    type: rest
    resource: 'KunstmaanRestUserBundle:User'
    defaults:
        _format: json
    prefix:   /api

kunstmaan_api_roles:
    type: rest
    resource: 'KunstmaanRestUserBundle:Role'
    defaults:
        _format: json
    prefix:   /api

kunstmaan_api_groups:
    type: rest
    resource: 'KunstmaanRestUserBundle:Group'
    defaults:
        _format: json
    prefix:   /api
