services:
    Kunstmaan\Rest\UserBundle\Controller\UserController:
        public: true
        arguments:
            - '@doctrine'
        calls:
            - [setViewHandler, ['@fos_rest.view_handler.default']]
