nelmio_api_doc:
  documentation:
    components:
      schemas:
        RoleList:
          properties:
            roles:
              type: "array"
              roles:
                allOf:
                  - $ref: '#/components/schemas/Role'
          title: "RoleList"
          required: ["roles"]
          type: "object"

        Role:
          title: "Role"
          type: "object"
          properties:
            role:
              type: "string"

        GroupList:
          properties:
            groups:
              type: "array"
              roles:
                allOf:
                  - $ref: '#/components/schemas/Group'
          title: "GroupList"
          required: ["groups"]
          type: "object"

        Group:
          title: "Group"
          type: "object"
          properties:
            name:
              type: "string"
            roles:
              type: "array"
              roles:
                allOf:
                  - $ref: '#/components/schemas/Role'

        UserList:
          properties:
            users:
              type: "array"
              users:
                allOf:
                  - $ref: '#/components/schemas/User'
          title: "UserList"
          required: ["users"]
          type: "object"

        User:
          title: "User"
          type: "object"
          properties:
            username:
              type: "string"
            email:
              type: "string"
            groups:
              type: "array"
            enabled:
              type: "boolean"
            adminLocale:
              type: "boolean"

        PutUser:
          title: "PutUser"
          type: "object"
          properties:
            username:
              type: "string"
            email:
              type: "string"
            groups:
              type: "array"
            enabled:
              type: "boolean"
            adminLocale:
              type: "string"
            password:
              type: "string"
            passwordConfirm:
              type: "string"

        PostUser:
          title: "PostUser"
          type: "object"
          properties:
            username:
              type: "string"
            email:
              type: "string"
            groups:
              type: "array"
            adminLocale:
              type: "string"
            password:
              type: "string"
            passwordConfirm:
              type: "string"

