Kunstmaan\MediaBundle\Entity\Folder:
  exclusion_policy: ALL
  properties:
      id:
          expose: true
      name:
          expose: true
      internalName:
          expose: true
          serialized_name: internalName
      rel:
          expose: true

  virtual_properties:
      parentId:
          exp: "object.getParent() ? object.getParent().getId():null"
          serialized_name: parentId
          type: integer
