Kunstmaan\MediaBundle\Entity\Folder:
  exclusion_policy: ALL
  properties:
      id:
          expose: true
      name:
          expose: true
      internalName:
        expose: true
      rel:
        expose: true

  virtual_properties:
      parent_id:
          exp: "object.getParent() ? object.getParent().getId():null"
          serialized_name: parent_id
          type: integer
