Kunstmaan\Rest\CoreBundle\Entity\RestUser:
  exclusion_policy: ALL
  properties:
      username:
          expose: true
      email:
          expose: true
      enabled:
          expose: true
      roles:
          expose: true
      adminLocale:
          serialized_name: adminLocale
          expose: true
