services:
    Kunstmaan\Rest\ArticleBundle\Controller\ArticleController:
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
        calls:
            - [setViewHandler, ['@fos_rest.view_handler.default']]
