nelmio_api_doc:
  documentation:
    definitions:
      Author:
        title: "Author"
        type: "object"
        properties:
          name:
            type: string
          link:
            type: string
