nelmio_api_doc:
  documentation:
    components:
      schemas:
        singleConfig:
          title: "singleConfig"
          type: "object"
          properties:
            id:
              type: "integer"
