kunstmaan_api_nodes:
    type: rest
    resource: 'kunstmaan_api.controller.nodes'
    defaults:
        _format: json

kunstmaan_api_pages:
    type: rest
    resource: 'kunstmaan_api.controller.pages'
    defaults:
        _format: json
