nelmio_api_doc:
  documentation:
    definitions:
      Node:
        title: "Node"
        type: "object"
        properties:
          id:
            type: "integer"
          hidden_from_nav:
            type: "boolean"
          ref_entity_name:
            type: "string"
          internal_name:
            type: "string"
          nodeTranslations:
            type: "array"
            items:
              allOf:
                - $ref: '#/definitions/NodeTranslation'

      NodeTranslation:
        title: "NodeTranslation"
        type: "object"
        properties:
          id:
            type: "integer"
          lang:
            type: "string"
          online:
            type: "boolean"
          weight:
            type: "integer"
          created:
            type: "string"
            format: "date-time"
          updated:
            type: "string"
            format: "date-time"

      NodeVersion:
        title: "nodeVersion"
        type: "object"
        properties:
          id:
            type: "integer"
          owner:
            type: "id"
          ref_id:
            type: "integer"
          ref_entity_name:
            type: "string"

      listNode:
        title: "listNode"
        type: "array"
        items:
          allOf:
            - $ref: '#/definitions/Node'

      ApiPagePart:
        title: "ApiPagePart"
        type: "object"
        properties:
          type:
            type: "string"
          pagepart:
            type: "object"
          context:
            type: "string"

      ApiContext:
        title: "ApiContext"
        type: "object"
        properties:
          name:
            type: "string"
          pageparts:
            type: "array"
            items:
              allOf:
                - $ref: '#/definitions/ApiPagePart'

      ApiPageTemplate:
        title: "ApiPageTemplate"
        type: "object"
        properties:
          name:
            type: "string"
          contexts:
            type: "array"
            items:
              allOf:
                - $ref: '#/definitions/ApiContext'

      ApiPage:
        title: "ApiPage"
        type: "object"
        properties:
          type:
            type: "string"
            example: 'Kunstmaan\SomeBundle\Entity\Pages\HomePage'
          page:
            type: "object"
          pageTemplate:
            type: "object"
            allOf:
              - $ref: '#/definitions/ApiPageTemplate'
          node:
            type: "object"
            allOf:
              - $ref: '#/definitions/Node'
          nodeTranslation:
            type: "object"
            allOf:
              - $ref: '#/definitions/NodeTranslation'
          nodeVersion:
            type: "object"
            allOf:
              - $ref: '#/definitions/NodeVersion'
