nelmio_api_doc:
  documentation:
    components:
      schemas:
        MenuList:
          properties:
            menus:
              type: "array"
              roles:
                allOf:
                  - $ref: '#/components/schemas/Menu'
          title: "MenuList"
          required: ["menus"]
          type: "object"

        MenuItemList:
          properties:
            menu-items:
              type: "array"
              roles:
                allOf:
                  - $ref: '#/components/schemas/MenuItem'
          title: "MenuItemList"
          required: ["menu-items"]
          type: "object"
        PostMenu:
          title: "PostMenu"
          type: "object"
          properties:
            name:
              type: "string"
              required: false
            locale:
              type: "string"
              required: false
        PostMenuItem:
          title: "PostMenu"
          type: "object"
          properties:
            name:
              type: "string"
              required: false
            locale:
              type: "string"
              required: false
        PutMenuItem:
          title: "PostMenu"
          type: "object"
          properties:
            name:
              type: "string"
              required: false
            locale:
              type: "string"
              required: false
        Menu:
          title: "Menu"
          type: "object"
          properties:
            id:
              type: "integer"
              required: false
            name:
              type: "string"
              required: false
            locale:
              type: "string"
              required: false

        MenuItem:
          title: "MenuItem"
          type: "object"
          properties:
            id:
              type: "integer"
              required: false
            menu:
              type: "object"
              allOf:
                - $ref: '#/components/schemas/Folder'
            nodeTranslation:
              type: "object"
              allOf:
                - $ref: '#/components/schemas/NodeTranslation'
            type:
              type: "string"
              required: false
            title:
              type: "string"
              required: false
            url:
              type: "string"
              required: false
            newWindow:
              type: "boolean"
              required: false
            lft:
              type: "integer"
              required: false
            rgt:
              type: "integer"
              required: false
            lvl:
              type: "integer"
              required: false
