KunstmaanUserManagementBundle_user_settings:
  resource: '@KunstmaanRestCoreBundle/Controller/AuthenticationController.php'
  type:     annotation
  prefix:   /%locale%/%kunstmaan_admin.admin_prefix%/settings/users