services:
  Kunstmaan\Rest\FormBundle\Controller\FormSubmissionController:
    public: true
    arguments:
      - '@doctrine'
    calls:
      - [ setViewHandler, [ '@fos_rest.view_handler.default' ] ]
      - [ setContainer, [ '@service_container' ] ]
