nelmio_api_doc:
  documentation:
    components:
      schemas:
        FormSubmissionList:
          properties:
            submissions:
              type: "array"
              items:
                allOf:
                  - $ref: '#/components/schemas/FormSubmission'
          title: "FormSubmisssionList"
          required: ["submissions"]
          type: "object"

        FormSubmission:
          title: "FormSubmission"
          type: "object"
          properties:
            id:
              type: "integer"
            lang:
              type: "string"
            created:
              type: "string"
            ipAddress:
              type: "string"
            fields:
              type: "sting"
            node:
              type: "object"
