Kunstmaan\MenuBundle\Entity\BaseMenu:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
    name:
      expose: true
      type: string
    locale:
      expose: true
      type: string
