Kunstmaan\NodeBundle\Entity\Node:
  exclusion_policy: ALL

  properties:
    hiddenFromNav:
      expose: true
      groups: [edit]
    internalName:
      expose: true
      groups: [edit]
    refEntityName:
      expose: true
      groups: [edit]

  relations:
    -
      rel: self
      href: expr('/api/nodes/' ~ object.getId())
