kunstmaan_api_nodes:
  type: annotation
  resource: '@KunstmaanRestNodeBundle/Controller/NodesController.php'
  defaults:
    _format: json
  prefix: /api

kunstmaan_api_pages:
  type: annotation
  resource: '@KunstmaanRestNodeBundle/Controller/PagesController.php'
  defaults:
    _format: json
  prefix: /api
