nelmio_api_doc:
  documentation:
    components:
        schemas:
            singleRedirect:
                title: "singleRedirect"
                type: "object"
                properties:
                id:
                    type: "integer"
                    required: false
                domain:
                    required: true
                    type: "string"
                origin:
                    required: true
                    type: "string"
                note:
                    required: true
                    type: "string"
                target:
                    required: true
                    type: "string"
                permanent:
                    required: true
                    type: "boolean"

            listRedirect:
                properties:
                folder:
                    type: "array"
                    items:
                    allOf:
                        - $ref: '#/components/schemas/singleRedirect'
                title: "listRedirect"
                required: ["items"]
                type: "object"
