nelmio_api_doc:
  definitions:
    ErrorModel:
      title: "ErrorModel"
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
          example: "404"
        message:
          type: "string"
          example: "Not found"
        extraData:
          type: "array"
          items: []

    listNode:
      title: "listNode"
      type: "array"
      items:
        allOf:
          - $ref: '#/definitions/Node'
